# fly.toml app configuration file generated for tic-tac-toe-backends on 2023-06-28T11:40:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tic-tac-toe-backends"
primary_region = "dfw"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
