[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "api"
version = "1.0.0"
dynamic = ["authors", "dependencies", "description", "license"]