name: Run unit tests

on:
  push:
    branches:
      - "*"
    paths:
      - backends/**
      - frontends/**
      - library/**
      - .github/workflows/**
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install library
        run: python -m pip install library/

      - name: Install build dependencies
        working-directory: ./backends
        run: python -m pip install pyproject.toml

      - name: Install app dependencies
        working-directory: ./backends
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements.development.txt
          python -m pip install .

      - name: Run unit tests
        working-directory: ./backends
        run: python -m coverage run -m unittest discover tests

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-results
          path: e2e-results/
          retention-days: 30

  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

