name: Run unit tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - name: Install build dependencies
        working-directory: ./backends
        run: pip install pyproject.toml
      - name: Install app dependencies
        working-directory: ./backends
        run: pip install -r requirements.txt
      - name: Run unit tests
        working-directory: ./backends
        run: python -m unittest tests.app
